/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

/**
 *
 * @author Bruno Nicoletti
 */
public class RemoverCadastros extends javax.swing.JFrame {

    /**
     * Creates new form RemoverCadastros
     */
    public RemoverCadastros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RemoverAdmTextField = new javax.swing.JTextField();
        EntrarRemoverAtendentejButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RemoverAtendenteTextField = new javax.swing.JTextField();
        EntrarRemoverAdmjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RemoverPacienteTextField = new javax.swing.JTextField();
        ExitjButton1 = new javax.swing.JButton();
        EntrarRemoverPacientejButton = new javax.swing.JButton();
        ReturnjButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RemoverAdmTextField.setEditable(false);
        RemoverAdmTextField.setBackground(new java.awt.Color(204, 255, 204));
        RemoverAdmTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        RemoverAdmTextField.setText("       Remover Adm");
        RemoverAdmTextField.setBorder(new javax.swing.border.MatteBorder(null));
        RemoverAdmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverAdmTextFieldActionPerformed(evt);
            }
        });

        EntrarRemoverAtendentejButton.setText("Ir ");
        EntrarRemoverAtendentejButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntrarRemoverAtendentejButton.setContentAreaFilled(false);
        EntrarRemoverAtendentejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarRemoverAtendentejButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\Projeto_Faculdade\\src\\main\\java\\br\\com\\view\\logo vaccination.png")); // NOI18N

        RemoverAtendenteTextField.setEditable(false);
        RemoverAtendenteTextField.setBackground(new java.awt.Color(204, 255, 204));
        RemoverAtendenteTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        RemoverAtendenteTextField.setText("   Remover Atendente");
        RemoverAtendenteTextField.setBorder(new javax.swing.border.MatteBorder(null));
        RemoverAtendenteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverAtendenteTextFieldActionPerformed(evt);
            }
        });

        EntrarRemoverAdmjButton.setText("Ir ");
        EntrarRemoverAdmjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntrarRemoverAdmjButton.setContentAreaFilled(false);
        EntrarRemoverAdmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarRemoverAdmjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 25)); // NOI18N
        jLabel1.setText("Remoção de usuários");

        RemoverPacienteTextField.setEditable(false);
        RemoverPacienteTextField.setBackground(new java.awt.Color(204, 255, 204));
        RemoverPacienteTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        RemoverPacienteTextField.setText("   Remover Paciente");
        RemoverPacienteTextField.setBorder(new javax.swing.border.MatteBorder(null));
        RemoverPacienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverPacienteTextFieldActionPerformed(evt);
            }
        });

        ExitjButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\Projeto_Faculdade\\src\\main\\java\\br\\com\\view\\5a2245b1715e40.6948349115121955054644.png")); // NOI18N
        ExitjButton1.setBorder(null);
        ExitjButton1.setBorderPainted(false);
        ExitjButton1.setContentAreaFilled(false);
        ExitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjButton1ActionPerformed(evt);
            }
        });

        EntrarRemoverPacientejButton.setText("Ir ");
        EntrarRemoverPacientejButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntrarRemoverPacientejButton.setContentAreaFilled(false);
        EntrarRemoverPacientejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarRemoverPacientejButtonActionPerformed(evt);
            }
        });

        ReturnjButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\Projeto_Faculdade\\src\\main\\java\\br\\com\\view\\icone_seta_voltar.png")); // NOI18N
        ReturnjButton3.setBorderPainted(false);
        ReturnjButton3.setContentAreaFilled(false);
        ReturnjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnjButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReturnjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoverPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoverAdmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoverAtendenteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(EntrarRemoverPacientejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(EntrarRemoverAtendentejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(EntrarRemoverAdmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReturnjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExitjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RemoverPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EntrarRemoverPacientejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoverAtendenteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EntrarRemoverAtendentejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoverAdmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EntrarRemoverAdmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoverAdmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverAdmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverAdmTextFieldActionPerformed

    private void EntrarRemoverAtendentejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarRemoverAtendentejButtonActionPerformed
        RemoverCadastroAtendente frame = new RemoverCadastroAtendente();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntrarRemoverAtendentejButtonActionPerformed

    private void RemoverAtendenteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverAtendenteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverAtendenteTextFieldActionPerformed

    private void EntrarRemoverAdmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarRemoverAdmjButtonActionPerformed
        RemoverCadastroAdm frame = new RemoverCadastroAdm();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntrarRemoverAdmjButtonActionPerformed

    private void RemoverPacienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverPacienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverPacienteTextFieldActionPerformed

    private void ExitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitjButton1ActionPerformed

    private void EntrarRemoverPacientejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarRemoverPacientejButtonActionPerformed
       RemoverCadastroPaciente frame = new RemoverCadastroPaciente();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntrarRemoverPacientejButtonActionPerformed

    private void ReturnjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnjButton3ActionPerformed
        TelaAdmCentral frame = new TelaAdmCentral();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnjButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntrarRemoverAdmjButton;
    private javax.swing.JButton EntrarRemoverAtendentejButton;
    private javax.swing.JButton EntrarRemoverPacientejButton;
    private javax.swing.JButton ExitjButton1;
    private javax.swing.JTextField RemoverAdmTextField;
    private javax.swing.JTextField RemoverAtendenteTextField;
    private javax.swing.JTextField RemoverPacienteTextField;
    private javax.swing.JButton ReturnjButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
