/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

/**
 *
 * @author Bruno Nicoletti
 */
public class TelaAdmCentral extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmCentral
     */
    public TelaAdmCentral() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        CadastrarPacienteTextField = new javax.swing.JTextField();
        EntrarCadastroPacientejButton = new javax.swing.JButton();
        CadastrarAdmTextField = new javax.swing.JTextField();
        EntrarCadastroAtendentejButton = new javax.swing.JButton();
        CadastrarAtendenteTextField = new javax.swing.JTextField();
        EntrarCadastroAdmjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ExitjButton1 = new javax.swing.JButton();
        CadastrarAdmTextField1 = new javax.swing.JTextField();
        EntrarRemoverCadastrojButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\Projeto_Faculdade\\src\\main\\java\\br\\com\\view\\logo vaccination.png")); // NOI18N

        CadastrarPacienteTextField.setEditable(false);
        CadastrarPacienteTextField.setBackground(new java.awt.Color(204, 255, 204));
        CadastrarPacienteTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        CadastrarPacienteTextField.setText("   Cadastrar Paciente");
        CadastrarPacienteTextField.setBorder(new javax.swing.border.MatteBorder(null));
        CadastrarPacienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarPacienteTextFieldActionPerformed(evt);
            }
        });

        EntrarCadastroPacientejButton.setText("Ir ");
        EntrarCadastroPacientejButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntrarCadastroPacientejButton.setContentAreaFilled(false);
        EntrarCadastroPacientejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarCadastroPacientejButtonActionPerformed(evt);
            }
        });

        CadastrarAdmTextField.setEditable(false);
        CadastrarAdmTextField.setBackground(new java.awt.Color(204, 255, 204));
        CadastrarAdmTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        CadastrarAdmTextField.setText("       Cadastrar Adm");
        CadastrarAdmTextField.setBorder(new javax.swing.border.MatteBorder(null));
        CadastrarAdmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAdmTextFieldActionPerformed(evt);
            }
        });

        EntrarCadastroAtendentejButton.setText("Ir ");
        EntrarCadastroAtendentejButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntrarCadastroAtendentejButton.setContentAreaFilled(false);
        EntrarCadastroAtendentejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarCadastroAtendentejButtonActionPerformed(evt);
            }
        });

        CadastrarAtendenteTextField.setEditable(false);
        CadastrarAtendenteTextField.setBackground(new java.awt.Color(204, 255, 204));
        CadastrarAtendenteTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        CadastrarAtendenteTextField.setText("  Cadastrar Atendente");
        CadastrarAtendenteTextField.setBorder(new javax.swing.border.MatteBorder(null));
        CadastrarAtendenteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAtendenteTextFieldActionPerformed(evt);
            }
        });

        EntrarCadastroAdmjButton.setText("Ir ");
        EntrarCadastroAdmjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntrarCadastroAdmjButton.setContentAreaFilled(false);
        EntrarCadastroAdmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarCadastroAdmjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 25)); // NOI18N
        jLabel1.setText("Central Administrador");

        ExitjButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\Projeto_Faculdade\\src\\main\\java\\br\\com\\view\\5a2245b1715e40.6948349115121955054644.png")); // NOI18N
        ExitjButton1.setBorder(null);
        ExitjButton1.setBorderPainted(false);
        ExitjButton1.setContentAreaFilled(false);
        ExitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjButton1ActionPerformed(evt);
            }
        });

        CadastrarAdmTextField1.setEditable(false);
        CadastrarAdmTextField1.setBackground(new java.awt.Color(204, 255, 204));
        CadastrarAdmTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        CadastrarAdmTextField1.setText("    Remover Cadastros");
        CadastrarAdmTextField1.setBorder(new javax.swing.border.MatteBorder(null));
        CadastrarAdmTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAdmTextField1ActionPerformed(evt);
            }
        });

        EntrarRemoverCadastrojButton1.setText("Ir ");
        EntrarRemoverCadastrojButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EntrarRemoverCadastrojButton1.setContentAreaFilled(false);
        EntrarRemoverCadastrojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarRemoverCadastrojButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastrarPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarAdmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarAtendenteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarAdmTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(EntrarCadastroPacientejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(EntrarCadastroAtendentejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(EntrarCadastroAdmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(EntrarRemoverCadastrojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CadastrarPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EntrarCadastroPacientejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CadastrarAtendenteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EntrarCadastroAtendentejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CadastrarAdmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EntrarCadastroAdmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(CadastrarAdmTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ExitjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(EntrarRemoverCadastrojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarPacienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarPacienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarPacienteTextFieldActionPerformed

    private void EntrarCadastroPacientejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarCadastroPacientejButtonActionPerformed
        CadastrarPaciente frame = new CadastrarPaciente();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntrarCadastroPacientejButtonActionPerformed

    private void CadastrarAdmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAdmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarAdmTextFieldActionPerformed

    private void EntrarCadastroAtendentejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarCadastroAtendentejButtonActionPerformed
        CadastrarAtendente frame = new CadastrarAtendente();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntrarCadastroAtendentejButtonActionPerformed

    private void CadastrarAtendenteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAtendenteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarAtendenteTextFieldActionPerformed

    private void ExitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitjButton1ActionPerformed

    private void CadastrarAdmTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAdmTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarAdmTextField1ActionPerformed

    private void EntrarCadastroAdmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarCadastroAdmjButtonActionPerformed
        CadastroAdm frame = new CadastroAdm();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntrarCadastroAdmjButtonActionPerformed

    private void EntrarRemoverCadastrojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarRemoverCadastrojButton1ActionPerformed
        RemoverCadastros frame = new RemoverCadastros();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntrarRemoverCadastrojButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdmCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CadastrarAdmTextField;
    private javax.swing.JTextField CadastrarAdmTextField1;
    private javax.swing.JTextField CadastrarAtendenteTextField;
    private javax.swing.JTextField CadastrarPacienteTextField;
    private javax.swing.JButton EntrarCadastroAdmjButton;
    private javax.swing.JButton EntrarCadastroAtendentejButton;
    private javax.swing.JButton EntrarCadastroPacientejButton;
    private javax.swing.JButton EntrarRemoverCadastrojButton1;
    private javax.swing.JButton ExitjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
