package br.com.view;

import br.com.dao.PacientesDAO;
import br.com.model.Pacientes;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class TelaRelatorio extends javax.swing.JFrame {

    public void listar() {
        PacientesDAO dao = new PacientesDAO();
        List<Pacientes> lista = dao.listarPacientes();
        DefaultTableModel dados = (DefaultTableModel) TabelaRelatorioPacientejTable1.getModel();
        dados.setNumRows(0);

        for (Pacientes p : lista) {
            dados.addRow(new Object[]{
                p.getNome(),
                p.getIdade(),
                p.getProfissao(),
                p.getEndereco(),
                p.getVacinado(),
                p.getDataDeVacinacao()
            });
        }
    }

    public void listarPorIdade(int idade1, int idade2) {
        PacientesDAO pd = new PacientesDAO();
        List<Pacientes> lista = pd.buscarData(idade1, idade2);
        DefaultTableModel dados = (DefaultTableModel) TabelaRelatorioPacientejTable1.getModel();
        dados.setNumRows(0);

        for (Pacientes p : lista) {
            dados.addRow(new Object[]{
                p.getNome(),
                p.getIdade(),
                p.getProfissao(),
                p.getEndereco(),
                p.getVacinado(),
                p.getDataDeVacinacao()
            });
        }
    }

    public TelaRelatorio() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) TabelaRelatorioPacientejTable1.getModel();
        TabelaRelatorioPacientejTable1.setRowSorter(new TableRowSorter(modelo));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GerarButton = new javax.swing.JButton();
        data2TextField = new javax.swing.JTextField();
        data1TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaRelatorioPacientejTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        voltarbutton = new javax.swing.JButton();
        sairbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GerarButton.setText("Gerar");
        GerarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarButtonActionPerformed(evt);
            }
        });

        data2TextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Insira a segunda idade"));
        data2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data2TextFieldActionPerformed(evt);
            }
        });

        data1TextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Insira a primeira idade"));
        data1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data1TextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setAutoscrolls(true);

        TabelaRelatorioPacientejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Idade", "Profissão ", "Endereço", "Vacinado", "Data de vacinação"
            }
        ));
        TabelaRelatorioPacientejTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaRelatorioPacientejTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaRelatorioPacientejTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\Projeto_Faculdade\\src\\main\\java\\br\\com\\view\\logo vaccination.png")); // NOI18N

        voltarbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\Projeto_Faculdade\\src\\main\\java\\br\\com\\view\\icone_seta_voltar.png")); // NOI18N
        voltarbutton.setBorder(null);
        voltarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarbuttonActionPerformed(evt);
            }
        });

        sairbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\Projeto_Faculdade\\src\\main\\java\\br\\com\\view\\5a2245b1715e40.6948349115121955054644.png")); // NOI18N
        sairbutton.setBorder(null);
        sairbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(data1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(data2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(GerarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addComponent(voltarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sairbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(data1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(data2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(GerarButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voltarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sairbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaRelatorioPacientejTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaRelatorioPacientejTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaRelatorioPacientejTable1MouseClicked

    private void GerarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarButtonActionPerformed

        listarPorIdade(Integer.parseInt(data1TextField.getText()), Integer.parseInt(data2TextField.getText()));

    }//GEN-LAST:event_GerarButtonActionPerformed

    private void data1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data1TextFieldActionPerformed

    private void data2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data2TextFieldActionPerformed

    private void voltarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarbuttonActionPerformed
        ConfirmarVacina frame = new ConfirmarVacina();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarbuttonActionPerformed

    private void sairbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairbuttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GerarButton;
    private javax.swing.JTable TabelaRelatorioPacientejTable1;
    private javax.swing.JTextField data1TextField;
    private javax.swing.JTextField data2TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sairbutton;
    private javax.swing.JButton voltarbutton;
    // End of variables declaration//GEN-END:variables
}
