
package br.com.viewTest;

import br.com.dao.AdministradorDAO;
import br.com.dao.AtendenteDAO;
import br.com.dao.PacientesDAO;
import br.com.model.Administrador;
import br.com.model.Atendente;
import br.com.model.Pacientes;


public class TelaAdministrador extends javax.swing.JFrame {

    /** Creates new form TelaAdministrador */
    public TelaAdministrador() {
        super("Vaccionation System Covid-19"); 
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        enderecoTextField = new javax.swing.JTextField();
        profissaoTextField = new javax.swing.JTextField();
        idadeTextField = new javax.swing.JTextField();
        cadastrarPacButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nomeAdmTextField = new javax.swing.JTextField();
        loginAdmTextField = new javax.swing.JTextField();
        senhaAdmTextField = new javax.swing.JTextField();
        sairAdmButton = new javax.swing.JButton();
        CadastrarAdmButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nomeAteTextField = new javax.swing.JTextField();
        loginAteTextField = new javax.swing.JTextField();
        senhaAteTextField = new javax.swing.JTextField();
        sairAteButton = new javax.swing.JButton();
        cadastrarAtendenteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane2.setLayout(new java.awt.BorderLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setLayout(new javax.swing.OverlayLayout(jDesktopPane1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\ProjetoUsj\\src\\main\\java\\br\\com\\view\\icone-vacina-covid.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, 120));

        nomeTextField.setBackground(new java.awt.Color(204, 204, 204));
        nomeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Nome ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 360, 50));

        enderecoTextField.setBackground(new java.awt.Color(204, 204, 204));
        enderecoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel2.add(enderecoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 360, 50));

        profissaoTextField.setBackground(new java.awt.Color(204, 204, 204));
        profissaoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Profissão (0-Não é da area da saude/1-Area da saude)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel2.add(profissaoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 360, 50));

        idadeTextField.setBackground(new java.awt.Color(204, 204, 204));
        idadeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Idade ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel2.add(idadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 360, 50));

        cadastrarPacButton.setBackground(new java.awt.Color(102, 102, 102));
        cadastrarPacButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        cadastrarPacButton.setText("Cadastrar ");
        cadastrarPacButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        cadastrarPacButton.setContentAreaFilled(false);
        cadastrarPacButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPacButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cadastrarPacButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 180, 37));

        sairButton.setBackground(new java.awt.Color(204, 204, 204));
        sairButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        sairButton.setText("Sair ");
        sairButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        sairButton.setContentAreaFilled(false);
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        jPanel2.add(sairButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 410, 170, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\ProjetoUsj\\src\\main\\java\\br\\com\\view\\imagem_tela_cadastro.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        jTabbedPane1.addTab("Cadastrar Paciente ", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\ProjetoUsj\\src\\main\\java\\br\\com\\view\\icone-vacina-covid.png")); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, 120));

        nomeAdmTextField.setBackground(new java.awt.Color(204, 204, 204));
        nomeAdmTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Nome ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        nomeAdmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAdmTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(nomeAdmTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 310, 50));

        loginAdmTextField.setBackground(new java.awt.Color(204, 204, 204));
        loginAdmTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel3.add(loginAdmTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 310, 50));

        senhaAdmTextField.setBackground(new java.awt.Color(204, 204, 204));
        senhaAdmTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel3.add(senhaAdmTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 310, 50));

        sairAdmButton.setBackground(new java.awt.Color(204, 204, 204));
        sairAdmButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        sairAdmButton.setText("Sair ");
        sairAdmButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        sairAdmButton.setContentAreaFilled(false);
        sairAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairAdmButtonActionPerformed(evt);
            }
        });
        jPanel3.add(sairAdmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 104, 37));

        CadastrarAdmButton.setBackground(new java.awt.Color(102, 102, 102));
        CadastrarAdmButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        CadastrarAdmButton.setText("Cadastrar ");
        CadastrarAdmButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        CadastrarAdmButton.setContentAreaFilled(false);
        CadastrarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAdmButtonActionPerformed(evt);
            }
        });
        jPanel3.add(CadastrarAdmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 104, 37));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\ProjetoUsj\\src\\main\\java\\br\\com\\view\\imagem_tela_cadastro.png")); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        jTabbedPane1.addTab("Cadastrar Administrador ", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\ProjetoUsj\\src\\main\\java\\br\\com\\view\\icone-vacina-covid.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, 120));

        nomeAteTextField.setBackground(new java.awt.Color(204, 204, 204));
        nomeAteTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Nome ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        nomeAteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAteTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nomeAteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 310, 50));

        loginAteTextField.setBackground(new java.awt.Color(204, 204, 204));
        loginAteTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        loginAteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAteTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(loginAteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 310, 50));

        senhaAteTextField.setBackground(new java.awt.Color(204, 204, 204));
        senhaAteTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.add(senhaAteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 310, 50));

        sairAteButton.setBackground(new java.awt.Color(204, 204, 204));
        sairAteButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        sairAteButton.setText("Sair ");
        sairAteButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        sairAteButton.setContentAreaFilled(false);
        sairAteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairAteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sairAteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 104, 37));

        cadastrarAtendenteButton.setBackground(new java.awt.Color(102, 102, 102));
        cadastrarAtendenteButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        cadastrarAtendenteButton.setText("Cadastrar ");
        cadastrarAtendenteButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        cadastrarAtendenteButton.setContentAreaFilled(false);
        cadastrarAtendenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAtendenteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarAtendenteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 104, 37));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\rocha\\OneDrive\\Documentos\\Estudos\\Faculdade\\1-Semestre\\Programação de So\\Projeto Java\\ProjetoUsj\\src\\main\\java\\br\\com\\view\\imagem_tela_cadastro.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        jTabbedPane1.addTab("Cadastrar Atendente", jPanel1);

        jDesktopPane1.add(jTabbedPane1);

        jDesktopPane2.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarAtendenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAtendenteButtonActionPerformed
        Atendente ate = new Atendente();
        ate.setNome(nomeAteTextField.getText());
        ate.setLogin(loginAteTextField.getText());
        ate.setSenha(senhaAteTextField.getText());

        AtendenteDAO atd = new AtendenteDAO();
        atd.cadastrarAtendente(ate);
    }//GEN-LAST:event_cadastrarAtendenteButtonActionPerformed

    private void sairAteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairAteButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairAteButtonActionPerformed

    private void loginAteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAteTextFieldActionPerformed

    private void nomeAteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAteTextFieldActionPerformed

    private void CadastrarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAdmButtonActionPerformed
        Administrador adm = new Administrador();
        adm.setNome(nomeAdmTextField.getText());
        adm.setLogin(loginAdmTextField.getText());
        adm.setSenha(senhaAdmTextField.getText());

        AdministradorDAO ad = new AdministradorDAO();
        ad.cadastrarAdm(adm);
    }//GEN-LAST:event_CadastrarAdmButtonActionPerformed

    private void sairAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairAdmButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairAdmButtonActionPerformed

    private void nomeAdmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAdmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAdmTextFieldActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void cadastrarPacButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPacButtonActionPerformed
        Pacientes p = new Pacientes();
        p.setNome(nomeTextField.getText());
        p.setIdade(Integer.parseInt(idadeTextField.getText()));
        p.setProfissao(Integer.parseInt(profissaoTextField.getText()));
        p.setEndereco(enderecoTextField.getText());

        PacientesDAO pd = new PacientesDAO();
        pd.cadastrarPacientes(p);
    }//GEN-LAST:event_cadastrarPacButtonActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarAdmButton;
    private javax.swing.JButton cadastrarAtendenteButton;
    private javax.swing.JButton cadastrarPacButton;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JTextField idadeTextField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField loginAdmTextField;
    private javax.swing.JTextField loginAteTextField;
    private javax.swing.JTextField nomeAdmTextField;
    private javax.swing.JTextField nomeAteTextField;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField profissaoTextField;
    private javax.swing.JButton sairAdmButton;
    private javax.swing.JButton sairAteButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextField senhaAdmTextField;
    private javax.swing.JTextField senhaAteTextField;
    // End of variables declaration//GEN-END:variables

}
